### ISSUE TITLE
action='count' and other action= commands fail

### ISSUE THREAD

**Issue by sailuo** [swansonk14/typed-argument-parser#23]
```
class MyArgumentParser(Tap):
    debug: int = 0 # debug level

    def add_arguments(self):
        self.add_argument('-D', '--debug', action='count')
```
This code will fails, because class _CountAction doesn't accept the "type" parameter. Please check the following error message.

> Traceback (most recent call last):
  File "./main.py", line 52, in <module>
    args = MyArgumentParser().parse_args(); print(args)
  File "/Users/lsai/Library/Python/3.7/lib/python/site-packages/tap/tap.py", line 86, in __init__
    self._add_arguments()  # Adds all arguments in order to self
  File "/Users/lsai/Library/Python/3.7/lib/python/site-packages/tap/tap.py", line 225, in _add_arguments
    self._add_argument(*name_or_flags, **kwargs)
  File "/Users/lsai/Library/Python/3.7/lib/python/site-packages/tap/tap.py", line 212, in _add_argument
    super(Tap, self).add_argument(*name_or_flags, **kwargs)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 1353, in add_argument
    action = action_class(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'type'

**Comment by martinjm97** [comment]
Thank you for reporting this issue! We found that Tap doesn't play well with `action=x`. It'll be fixed in the next few days.
