### ISSUE TITLE
import gives AttributeError: __args__ 

### ISSUE THREAD

**Issue by timhemel** [swansonk14/typed-argument-parser#55]
When importing the library from python, I get an AttributeError:

```
$ python3
Python 3.9.5 (default, May  4 2021, 00:00:00)
[GCC 10.3.1 20210422 (Red Hat 10.3.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tap import Tap
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tim/.local/lib/python3.9/site-packages/tap/__init__.py", line 2, in <module>
    from tap.tap import Tap
  File "/home/tim/.local/lib/python3.9/site-packages/tap/tap.py", line 35, in <module>
    EMPTY_TYPE = get_args(List)[0] if len(get_args(List)) > 0 else tuple()
  File "/home/tim/.local/lib/python3.9/site-packages/typing_inspect.py", line 471, in get_args
    res = tp.__args__
  File "/usr/lib64/python3.9/typing.py", line 694, in __getattr__
    raise AttributeError(attr)
AttributeError: __args__
>>>
```
Version installed:

```
typed-argument-parser==1.6.2
```

**Comment by timhemel** [comment]
It looks like `List` in `get_args` needs a type argument, such as `List[None]` or `List[int]`.

**Comment by martinjm97** [comment]
Yes!
https://github.com/ilevkivskyi/typing_inspect/issues/73

For now we should freeze the version of `typing_inspect` to 0.6.0 to avoid this issue. Thank you for bringing this up!

**Comment by martinjm97** [comment]
Should be resolved by https://github.com/swansonk14/typed-argument-parser/commit/f03681e7fa91f96af8ab5144381a81120a9ecf51.
